include: package:dcm_presets/all.yaml

dcm:
  rules:
    - banned-usage:
        entries:
          # SharedPreferences control
          - name: SharedPreferences.getInstance
            description:
              'Use LocalStorage service from DI instead of direct
              SharedPreferences access.'
          - name: SharedPreferences.setString
            description:
              'Use LocalStorage.write() for consistent key management and
              encryption.'
          - name: SharedPreferences.getString
            description:
              'Use LocalStorage.read() for consistent key management.'

          # Secure storage
          - type: FlutterSecureStorage
            entries:
              - name: new
                description:
                  'Use SecureStorage service from DI for consistent secure
                  storage access.'
