// coverage:ignore-file
// GENERATED CODE - DO NOT MANUALLY EDIT
// This file is generated by freezed

part of 'product.dart';

// ignore: unused_element
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$Product {
  String get id;
  String get name;
  double get price;
}
