// GENERATED CODE - DO NOT MANUALLY EDIT
// This file is generated by build_runner

part of 'user.dart';

// ignore: unused_element
User _$UserFromJson(Map<String, dynamic> json) {
  return User(
    id: json['id'] as String,
    name: json['name'] as String,
  );
}

// ignore: unused_element
Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
    };
